version: "3.1"
services:
  app:
    container_name: go-root
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${DOCKER_APP_PORT}
    restart: always
    networks:
      - app-network

networks:
  app-network:
    external: 
      name: nat
